### ISSUE TITLE
requirements for test

### ISSUE THREAD

**Issue by nadavru1029** [wuhuikai/GP-GAN#24]
installed cupy 6.3.0 and chainer 6.3.0 as requested, getting the following error for running run_gp_gan.py:

File "cupy/core/core.pyx", line 2284, in cupy.core.core.tensordot_core
  File "cupy/core/core.pyx", line 2383, in cupy.core.core.tensordot_core
  File "cupy/cuda/cublas.pyx", line 927, in cupy.cuda.cublas.sgemmEx
  File "cupy/cuda/cublas.pyx", line 308, in cupy.cuda.cublas.check_status
cupy.cuda.cublas.CUBLASError: CUBLAS_STATUS_EXECUTION_FAILED

List of modules installed:

chainer==6.3.0
cupy==6.3.0
cycler==0.10.0
decorator==4.4.2
fastrlock==0.5
filelock==3.0.12
imageio==2.9.0
kiwisolver==1.3.1
matplotlib==3.3.3
networkx==2.5
numpy==1.19.4
Pillow==8.0.1
pkg-resources==0.0.0
protobuf==3.7.1
pyparsing==2.4.7
python-dateutil==2.8.1
PyWavelets==1.1.1
scikit-image==0.15.0
scipy==1.5.4
six==1.15.0
typing==3.6.6
typing-extensions==3.6.6

**Comment by wuhuikai** [comment]
It seems that cupy is not installed correctly.

**Comment by lifengheng** [comment]
I encountered the same problem.Could you share the version of your cuda and cudnn.Thanks

**Comment by wuhuikai** [comment]
I didn't remember the corresponding cuda and cudnn version. Try to install the latest version in 2016.

**Comment by lifengheng** [comment]
> I didn't remember the corresponding cuda and cudnn version. Try to install the latest version in 2016.
Thanks for replying. I think I probably solve the problem by installing cupy-cuda101(cupy==8.2.0) instead of  cupy==6.3.0. My cuda version is 10.1, so I tried cupy-cuda101 and it works though it issued a warning that the cupy verison is not compatible with chainer.

**Comment by wuhuikai** [comment]
Great, maybe you can update chainer and see if this repo can run with the latest chainer.

**Comment by 1162197376** [comment]
I also encountered the same problem, but the difference is that blending_gan.npz works, but unsupervised_blending_gan.npz reports CUBLASError.Want to ask what is going on here?

**Comment by wuhuikai** [comment]
This is a really old project, I can not figure out problems like this one.
